🔪Kitchen Sink Examples
CommandCodeAI/command-code pull request #130
Opened 2018-12-26 00:49 UTC by braginteractive

Here is the start of the Kitchen Sink example. Let me know what you think/suggestions. 

<img width="281" alt="screen shot 2018-12-25 at 6 46 49 pm" src="https://user-images.githubusercontent.com/2836834/50427772-92e22200-0875-11e9-8f2c-05a73091f440.png">

2018-12-26 05:48 UTC, ahmadawais requested changes
Thanks for all the effort you put in this block @braginteractive — I have reviewed it and left comments. Let's improve these sections before merging. 

Kudos! 👍

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/init.php
> +// Add custom block category
Add a period `.` at the end of comments.

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/README.md
> +### What/How?
1. This `README.md` file has a  lot of irrelevant info about the a11y example remove that.
2. Explain what features you have added + docs links

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +// Register editor components
Document addition of each new module. Don't be afraid of commenting about everything. This example is meant to teach people.

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> + * Register: aa Gutenberg Block.
`aa Gutenberg Block.`   Maybe rename that `aa` here. Docs should be up to date. :)

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +		// Adds block supports: https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#supports-optional
Add Multiline comments explaining everything and then at the end of the comment give docs links. `Adds block supports` doesn't help anyone. Explain the What/Why/How.

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +	attributes: kitchenAttributes, // Use attributes from line 42
I don't see a benefit in creating `kitchenAttributes` constant. Instead just add it all here.

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +		// Setup the attributes for the editor
Wrong comment. Explain what is happening here. Obj deconstruction?

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +			attributes,
`attributes` is already there? Why including it again?

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +		return [
Explain in details how the JSX going to be for the block. The real HTML and the Wrappers. Without this explanation example is not going to be helpful.

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +							checked={!!exampleToggle}
Explain `!!` — remember WordPress community is new to JS. :)

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +		// Attributes for the frontend
Same as above. Detailed docs would be awesome! 💯

2018-12-26 05:48 UTC, ahmadawais commented on examples/06-kitchen-sink/src/block/block.js
> +			attributes,
Again repetition of `attributes` is wrong — JS objects should have unique keys.

2018-12-26 05:49 UTC, ahmadawais commented
One more thing, @braginteractive — kindly use [Emoji-log](https://github.com/ahmadawais/Emoji-Log) for writing git commits.

2018-12-26 18:09 UTC, braginteractive commented
@ahmadawais I am learning some of this myself. Any examples and improvements that you can provide would help!

2018-12-28 16:36 UTC, ahmadawais commented
@braginteractive Trust yourself. You're making really good progress. Let's document and ship this Kitchen Sink Example next year.

2018-12-28 16:37 UTC, ahmadawais commented
Also go through the changes requested and resolve all of these 👍

2026-05-04 18:05 UTC, closed without merging